### PR TITLE
Sugarchain: fix: do not disconnect whitelisted peers during IBD

### LINKED ISSUE #95: IBD: disconnecting is better for safe?
https://github.com/sugarchain-project/sugarchain/blob/cbd806eaf3b3e15c64b334aa74b49107cd10e9c2/src/net_processing.cpp#L3591-L3595

its 17% faster IBD sync. but less safer than before.

https://github.com/sugarchain-project/sugarchain/pull/80/files

### PR DESCRIPTION
**Pull request by decryp2kanon**
### discussion
`Timeout downloading headers from peer=0, disconnecting` VS `Timeout downloading headers from whitelisted peer=0, not disconnecting`

### result: 9b5c0cb
- 9b5c0cb : `10:00 (16% faster)` :heavy_check_mark: 
- 827b0bd : `10:20 (12% faster)`
- cee8630 : `10:35 (10% faster)`
- old RC3 2a0ecad22bd3b2dffb649b2ef0ecb3ce89417bcc: `11:40`

### benchmark
image

9b5c0cb is the best

### traffic
image

### peers
image

### mid log
image

image

### Log for Timeout downloading
- 9b5c0cb
```
$ grep "Timeout downloading headers" /mnt/ssd120g/TEST-SUGAR/.sugarchain-9b5c0cb/debug.log 
2020-02-16 00:52:15 Timeout downloading headers from whitelisted peer=0, not disconnecting
2020-02-16 01:46:14 Timeout downloading headers from whitelisted peer=1, not disconnecting
2020-02-16 02:44:35 Timeout downloading headers from whitelisted peer=1, not disconnecting
2020-02-16 03:19:00 Timeout downloading headers from whitelisted peer=3, not disconnecting
2020-02-16 03:47:36 Timeout downloading headers from whitelisted peer=4, not disconnecting
2020-02-16 04:11:19 Timeout downloading headers from whitelisted peer=5, not disconnecting
2020-02-16 04:31:09 Timeout downloading headers from whitelisted peer=6, not disconnecting
```

- 827b0bd 
```
$ grep "Timeout downloading headers" /mnt/ssd120g/TEST-SUGAR/.sugarchain-827b0bd/debug.log
```
NO RESULTS

- cee8630
```
$ grep "Timeout downloading headers" /mnt/ssd120g/TEST-SUGAR/.sugarchain-cee8630/debug.log
2020-02-16 00:47:49 Timeout downloading headers from peer=0, disconnecting
2020-02-16 01:42:05 Timeout downloading headers from peer=1, disconnecting
2020-02-16 02:27:17 Timeout downloading headers from peer=2, disconnecting
2020-02-16 03:04:49 Timeout downloading headers from peer=3, disconnecting
2020-02-16 03:35:53 Timeout downloading headers from peer=8, disconnecting
2020-02-16 04:01:44 Timeout downloading headers from peer=5, disconnecting
2020-02-16 04:28:41 Timeout downloading headers from peer=25, disconnecting
```

### CODE REVIEW

**Comment by decryp2kanon** [comment]
`Timeout downloading headers from peer=0, disconnecting`

**Comment by decryp2kanon** [comment]
make check failed:
```
FAIL: test/test_sugarchain
==========================

Running 282 test cases...
test/DoS_tests.cpp(138): error in "stale_tip_peer_management": check connman->GetTryNewOutboundPeer() failed

*** 1 failure detected in test suite "Sugarchain Test Suite"
FAIL test/test_sugarchain (exit status: 201)
```

**Comment by decryp2kanon** [comment]
`Timeout downloading headers from whitelisted peer=0, not disconnecting`

**Comment by decryp2kanon** [comment]
# 1
image
image

# 2
image
image


# 3
image
image

**Comment by decryp2kanon** [comment]
last is the fastest
image

File: src/net_processing.cpp [hunk 1]
```diff
@@ -3581,7 +3581,7 @@ bool PeerLogicValidation::SendMessages(CNode* pto, std::atomic<bool>& interruptM
         // Check for headers sync timeouts
         if (state.fSyncStarted && state.nHeadersSyncTimeout < std::numeric_limits<int64_t>::max()) {
             // Detect whether this is a stalling initial-headers-sync peer
-            if (pindexBestHeader->GetBlockTime() <= GetAdjustedTime() - 24*60*60) {
+            if (pindexBestHeader->GetBlockTime() <= GetAdjustedTime() - (24*60*60)*120) { // FIXME.SUGAR // 120x bitcoin // prevent disconnect peers during IBD
```
Comment (decryp2kanon) [inline src/net_processing.cpp]: `Timeout downloading headers from peer=0, disconnecting` at sync 22% and 1 hour eslaped

**Comment by decryp2kanon** [comment]
```cpp
/** Time after which to disconnect, after waiting for a ping response (or inactivity). */
static const int TIMEOUT_INTERVAL = 20 * 60;
```
`ping timeout: 1200.038358s`
its fine.

**Comment by decryp2kanon** [comment]
7dd2e3e
image

**Comment by decryp2kanon** [comment]
8683428
image

**Comment by decryp2kanon** [comment]
f9d0998
image

**Comment by decryp2kanon** [comment]
no effect. cee(master merged) is the fastet
image

File: src/net.h [hunk 2]
```diff
@@ -56,7 +56,7 @@ static const unsigned int MAX_PROTOCOL_MESSAGE_LENGTH = 4 * 1000 * 1000;
 /** Maximum length of strSubVer in `version` message */
 static const unsigned int MAX_SUBVERSION_LENGTH = 256;
 /** Maximum number of automatic outgoing nodes */
-static const int MAX_OUTBOUND_CONNECTIONS = 8;
+static const int MAX_OUTBOUND_CONNECTIONS = 8*2; // FIXME.SUGAR // (was 8) increasing outbound to make sync faster
```
Comment (decryp2kanon) [inline src/net.h]: no effect. just increased traffic

File: src/net_processing.cpp (hunk 1 above)
Comment (decryp2kanon) [reply src/net_processing.cpp]: no effect.

**Comment by decryp2kanon** [comment]
NACK f9d0998
interesting, adding peers not helps IBD sync time. `8peers` vs `16peers` same sync speed. more peers only increase data traffic 2x

**Comment by decryp2kanon** [comment]
image

image

**Comment by decryp2kanon** [comment]
image

**Comment by decryp2kanon** [comment]
retest: 
cee8630 : 14:47
827b0bd : 14:00
9b5c0cb : 13:00

**Comment by decryp2kanon** [comment]
image

this test failed, due to low disk space on my system. i have to retest.

**Comment by decryp2kanon** [comment]
9b5c0cb vs 827b0bd vs cee8630

### mid results
9b5c0cb is `10.3%` faster than 827b0bd
9b5c0cb is `8.8%` faster than cee8630

### mid
image

### 1st
image

**Comment by decryp2kanon** [comment]
### result
image

9b5c0cb is the best

### traffic
image

### peers
image

**Comment by decryp2kanon** [comment]
https://github.com/sugarchain-project/sugarchain/issues/45

**Review by cryptozeny — APPROVED** [review]
Tested ACK 9b5c0cb

**Comment by volbil** [comment]
Looking good ACK

**Review by cryptozeny — APPROVED** [review]
Tested ACK feaabec58e5ef1ff6233a905e9a6362b682f02c0
